// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqGO-A4-afmyvmeBwo7mlS-VKtsYVTuZI',
    appId: '1:263374484001:web:b111409f160a35aaf2a960',
    messagingSenderId: '263374484001',
    projectId: 'massage-1294e',
    authDomain: 'massage-1294e.firebaseapp.com',
    storageBucket: 'massage-1294e.appspot.com',
    measurementId: 'G-FJ5QJZLTWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmoL8wUZC1XSV4UFIllkwV08ma6GBI6O4',
    appId: '1:263374484001:android:669dead95701bb24f2a960',
    messagingSenderId: '263374484001',
    projectId: 'massage-1294e',
    storageBucket: 'massage-1294e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxcX2YIW_dFjxsEXUoOS3rygIfFhMJ3Ds',
    appId: '1:263374484001:ios:525dc91065b5eaa0f2a960',
    messagingSenderId: '263374484001',
    projectId: 'massage-1294e',
    storageBucket: 'massage-1294e.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxcX2YIW_dFjxsEXUoOS3rygIfFhMJ3Ds',
    appId: '1:263374484001:ios:525dc91065b5eaa0f2a960',
    messagingSenderId: '263374484001',
    projectId: 'massage-1294e',
    storageBucket: 'massage-1294e.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqGO-A4-afmyvmeBwo7mlS-VKtsYVTuZI',
    appId: '1:263374484001:web:30a112a2abee2e07f2a960',
    messagingSenderId: '263374484001',
    projectId: 'massage-1294e',
    authDomain: 'massage-1294e.firebaseapp.com',
    storageBucket: 'massage-1294e.appspot.com',
    measurementId: 'G-XQB00SWV0D',
  );

}